version: '3.8'

services:
  # Database
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    networks:
      - database

  server:
    build:
      dockerfile: Dockerfile
    container_name: server
    networks:
      - database
      - backend
    environment:
      MONGODB_CONNECTION_STRING: 'mongodb://mongo:27017/'
      OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4317'
      OTEL_SERVICE_NAME: buf-connect-playground/server
      PORT: 3000
    ports:
      - 3000:3000

  # Collectors
  otel-collector:
    image: otel/opentelemetry-collector
    container_name: otel-collector
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - backend
    env_file:
      - .secret.env

networks:
  database:
    driver: bridge
  backend:
    driver: bridge
