receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:8888']

processors:
  batch:

exporters:
  otlp:
    endpoint: 'api.honeycomb.io:443'
    headers:
      'x-honeycomb-team': '${HONEYCOMB_API_KEY}'
  otlp/metrics:
    endpoint: 'api.honeycomb.io:443'
    headers:
      'x-honeycomb-team': '${HONEYCOMB_API_KEY}'
      'x-honeycomb-dataset': 'collector-dataset'
  logging:
    loglevel: debug

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    # metrics:
    #   receivers: [otlp, prometheus]
    #   processors: [batch]
    #   exporters: [otlp/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
